<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use App\Models\User;
use Auth;
use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Laravel\Fortify\Contracts\LogoutResponse;
use Laravel\Fortify\Http\Requests\LoginRequest;
use Laravel\Socialite\Facades\Socialite;
use Str;

#[Group('Authentication')]
final class AuthenticatedSessionController extends \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController
{
    /**
     * Login using provider.
     */
    public function provider(string $provider, Request $request): JsonResponse
    {
        $request->validate([
            'state' => ['required', 'string'],
            'code' => ['required', 'string'],
        ]);
        $request->session()->put('state', $request['state']);
        $request->session()->put('code', $request['code']);

        $googleUser = Socialite::driver('google')->user();
        $password = Str::random(16);

        $user = User::updateOrCreate([
            'email' => $googleUser->getEmail(),
        ], [
            'first_name' => $googleUser->getName(),
            'last_name' => null,
            'email' => $googleUser->getEmail(),
            'password' => $password,
            'google_id' => $googleUser->getId(),
        ]);

        Auth::login($user);

        return response()->json([
            'message' => 'Authenticated',
        ]);
    }

    /**
     * Login
     *
     * @unauthenticated
     */
    public function store(LoginRequest $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * Logout
     */
    public function destroy(Request $request): LogoutResponse
    {
        return parent::destroy($request); // TODO: Change the autogenerated stub
    }
}
