<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;
use Laravel\Fortify\Actions\ConfirmTwoFactorAuthentication;

#[Group('Authentication')]
final class ConfirmedTwoFactorAuthenticationController extends \Laravel\Fortify\Http\Controllers\ConfirmedTwoFactorAuthenticationController
{
    /**
     * Two-factor confirmation
     */
    public function store(Request $request, ConfirmTwoFactorAuthentication $confirm)
    {
        return parent::store($request, $confirm); // TODO: Change the autogenerated stub
    }
}
