<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;

#[Group('Authentication')]
final class EmailVerificationNotificationController extends \Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController
{
    /**
     * Send email verification
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
