<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\Password;
use Laravel\Fortify\Http\Controllers\NewPasswordController as FortifyNewPasswordController;

#[Group('Authentication')]
final class NewPasswordController extends FortifyNewPasswordController
{
    /**
     * Reset new password.
     *
     * @unauthenticated
     */
    public function store(Request $request): Responsable
    {
        $request->validate([
            'email' => ['required', 'string', 'email'],
            'token' => ['required'],
            'password' => ['required', 'string', Password::default(), 'confirmed'],
        ]);

        //        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
