<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use App\Models\User;
use Dedoc\Scramble\Attributes\Group;
use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

#[Group('Authentication')]
final class PasswordResetLinkController extends \Laravel\Fortify\Http\Controllers\PasswordResetLinkController
{
    /**
     * Send reset password link.
     *
     * @unauthenticated
     */
    public function store(Request $request): Responsable
    {
        $request->validate([
            'email' => [
                'required',
                'string',
                'email',
                Rule::exists(User::class, 'email'),
            ],
        ]);

        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
