<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;
use Laravel\Fortify\Actions\GenerateNewRecoveryCodes;

#[Group('Authentication')]
final class RecoveryCodeController extends \Laravel\Fortify\Http\Controllers\RecoveryCodeController
{
    /**
     * Display the recovery codes
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * Generate new recovery codes
     */
    public function store(Request $request, GenerateNewRecoveryCodes $generate)
    {
        return parent::store($request, $generate); // TODO: Change the autogenerated stub
    }
}
