<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Laravel\Fortify\Http\Requests\TwoFactorLoginRequest;

#[Group('Authentication')]
final class TwoFactorAuthenticatedSessionController extends \Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController
{
    /**
     * Two-factor login
     */
    public function store(TwoFactorLoginRequest $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
