<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;

#[Group('Authentication')]
final class TwoFactorQrCodeController extends \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController
{
    /**
     * Display the QR code for the user.
     */
    public function show(Request $request)
    {
        return parent::show($request); // TODO: Change the autogenerated stub
    }
}
