<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;

#[Group('Authentication')]
final class TwoFactorSecretKeyController extends \Laravel\Fortify\Http\Controllers\TwoFactorSecretKeyController
{
    /**
     * Display the two factor secret key.
     */
    public function show(Request $request)
    {
        return parent::show($request); // TODO: Change the autogenerated stub
    }
}
