<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\Request;
use Laravel\Fortify\Actions\DisableTwoFactorAuthentication;
use Laravel\Fortify\Actions\EnableTwoFactorAuthentication;

#[Group('Authentication')]
final class TwoFactorAuthenticationController extends \Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController
{
    /**
     * Enable two-factor
     */
    public function store(Request $request, EnableTwoFactorAuthentication $enable)
    {
        return parent::store($request, $enable); // TODO: Change the autogenerated stub
    }

    /**
     * Disable two-factor
     */
    public function destroy(Request $request, DisableTwoFactorAuthentication $disable)
    {
        return parent::destroy($request, $disable); // TODO: Change the autogenerated stub
    }
}
