<?php

declare(strict_types=1);

namespace App\Http\Controllers\Fortify;

use Dedoc\Scramble\Attributes\Group;
use Laravel\Fortify\Http\Requests\VerifyEmailRequest;

#[Group('Authentication')]
final class VerifyEmailController extends \Laravel\Fortify\Http\Controllers\VerifyEmailController
{
    /**
     * Verify email
     */
    public function __invoke(VerifyEmailRequest $request)
    {
        return parent::__invoke($request); // TODO: Change the autogenerated stub
    }
}
